# Generated by Django 2.2.5 on 2019-11-14 15:52

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'description', 'ingredients'], name='main_recipe_name_240bd1_gin'),
        ),
    ]
